name: Spain Fuel Prices Pipeline

on:
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: self-hosted

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_JOB_ID: ${{ secrets.DATABRICKS_JOB_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Python
        run: |
          python3 --version
          which python3

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Verify Databricks CLI
        run: |
          databricks version

      - name: Test Ministry website
        run: |
          curl -I https://sedeaplicaciones.minetur.gob.es

      - name: Test Fuel API
        run: |
          curl -v https://sedeaplicaciones.minetur.gob.es/ServiciosRESTCarburantes/PreciosCarburantes/EstacionesTerrestres/

      - name: Download Fuel Prices
        run: |
          python3 scripts/download_fuel_prices.py

      - name: Upload JSON to Databricks Volume
        run: |
          LATEST_FILE=$(ls -t data/raw/*.json | head -n 1)

          echo "Uploading: $LATEST_FILE"

          databricks fs cp \
            "$LATEST_FILE" \
            "dbfs:/Volumes/workspace/default/fuel_prices/raw/$(basename "$LATEST_FILE")" \
            --overwrite

      - name: Trigger Databricks Job
        run: |
          curl -X POST \
            "$DATABRICKS_HOST/api/2.1/jobs/run-now" \
            -H "Authorization: Bearer $DATABRICKS_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"job_id\": $DATABRICKS_JOB_ID}"
